lexware_sync_webhook:
    resource: '@KimaiLexwareSyncBundle/Controller/LexwareWebhookController.php'
    type: attribute

lexware_sync_triage:
    resource: '@KimaiLexwareSyncBundle/Controller/TriageController.php'
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
