services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\KimaiLexwareSyncBundle\:
        resource: '../../*'
        exclude:
            - '../../Entity/'
            - '../../Migrations/'
            - '../../Resources/'
            - '../../Tests/'

    KimaiPlugin\KimaiLexwareSyncBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    KimaiPlugin\KimaiLexwareSyncBundle\Service\LexwareApiClient:
        arguments:
            $apiKey: '%env(LEXWARE_API_KEY)%'
